---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: piwatch
  namespace: monitoring
spec:
  encryptedData:
    password: AgCuS4RFSpNPt3ALWLSXXGA2Cfo8rqTVirv4PBfmi0Gp4AwHgta1/7ImWlpBV0wAWUxu1Ecs2FiKqNM+VDK34iHzlTLAJ+PYL9D8r6wWjtJrhyg8qdMEA0sqlK5JXwoB+Jf5fVZ4qI9jYe5+5av/Bw+r5n0PBILl8jdQP9kZIX5g6yR6/guGN2lgYGO7GqTXbxhi3jJWQeul7BlGiB/VCUitnyirqHisPd2hqzfK2v3k7heR3yLT4PsaH1WnRPu5+jgo911zJMh+BSQghwDsvHWDwoKeGo9sgxnRwgUhpj8FMfa3MSGcrj/Vcoh/w+BgPfrdIpG6ylq2RufYN/4UsdelpTpwfGTy6Xb5bZc+JFzhTFnHG2VP/+9wuyipxfwqRh6LGar7ckFPkEvSdMWO0IKcpS0LctrfM/ClXce+Ksp6DsFxLkfhb9t8VRsUzll6FftM6tsQyMCclSuSGwqlszxO/yP5mhB/lmu9KiE/g4PYxOrA0xDw//29NvmCQ1DVpYIgFBQZ6CEQ6Bon7ZN3f8+qwlL7LK/3ZXaakKv77312KDxjq/vKS6xQOM2diYlRD5sYxvErV8zBx5LMQztSHVzvfYz+Q6TsJ2iopgFFn0pOJDcp6jHqg3KwDO1aKa3ye/g+pjwyarRbiCGLW5/t8S7zdryKob5tS2iCUQCnvjX+s6SZlr4GLilQJoiv8teGqdPRyFyV1RFXSmnfWcCKQhuHSA==
    secret: AgAsKA3xkJn0/CAilBMgWHFSecjbyTIgOws3ULhRvQoh839Kxv6K3PqRhtd/Te72Rzva2eZQLV8IogsqCImkxbXprko5htRJxz4+sNF9YGyAt+Yp72wcllpGo2WF5Za9XOsBig22IFIBv9q3UaCJwypSWBpfSInYA/Y8xarVB9eyfKDS94bLbcu9fx7sJ539U1zF1K+ffSnArAnSCIau/hxof2rSoDKItYV3lEEagTN/MDzS7YgeCx+hPn0grM7Wz1wTPc0rWwFQOx6WfhFoxWYje2bG8E/AQb40FWzQm1XfhH5VeZ0weyW6hFJ8NVzlE+TKUmSsaIG/zLJn8qQ0PqOTWmPAov/X/dcjGEQtAOdGpA2/qbYZ2KtkiEU9b2wbPx9RLku3ASGnA/HsLW4HiZeNg6oKTalqjRrCRFIJqvp8DlOjO34c63qNpcoesPwMvEy5ZGNZuLpvwPkhcUHh4T05rRrXPv8+hnry7o8Hf09AaKDdgSQtTkkNEYk31ywA9GX8fC/MLrUnOEorFgcOIx84SL3kMlnEs78TlZrRmlCh0TCT8DmoDKZJJiVHOfQeuY/NIs/xkWuu9WnYXZEI7Q4NXzHZqfQb0OiP31THMiEerafOeKj7+mkuITw+re/gOQMOfUPDzN1CKI7cKAJKOG0dxC7oJNZMqeOTLoTPy1H6LoMi/px5Fj590lzUrL+GN2cl4dKTxbIWzoEBiehE9wuz7+7JQ5bVFygoLvldu/oNHWXorXsAghf0+muIw5+QjBBttHGJlU3K16zwneUtUn3z
  template:
    metadata:
      name: piwatch
      namespace: monitoring
    type: Opaque
